# Generated by Django 6.0.3 on 2026-03-18 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyTree', '0002_person_gender_person_husband_person_spouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='wife',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wife_links', to='familyTree.person'),
        ),
    ]
