# Generated by Django 6.0.3 on 2026-04-15 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyTree', '0005_person_biography_person_birth_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='adoptive_father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adopted_children_father', to='familyTree.person'),
        ),
        migrations.AddField(
            model_name='person',
            name='adoptive_mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adopted_children_mother', to='familyTree.person'),
        ),
        migrations.CreateModel(
            name='PersonMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='person_media/')),
                ('media_type', models.CharField(choices=[('PHOTO', 'Photo'), ('DOCUMENT', 'Document')], default='PHOTO', max_length=16)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='familyTree.person')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('MARRIAGE', 'Marriage'), ('PARTNER', 'Partner')], default='MARRIAGE', max_length=16)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DIVORCED', 'Divorced'), ('SEPARATED', 'Separated'), ('WIDOWED', 'Widowed'), ('ENDED', 'Ended')], default='ACTIVE', max_length=16)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_person1', to='familyTree.person')),
                ('person2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_person2', to='familyTree.person')),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
            },
        ),
    ]
