# Generated by Django 6.0.3 on 2026-04-19 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familyTree', '0007_person_relationship_indexes_and_constraint'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='person',
            new_name='familyTree__last_na_496716_idx',
            old_name='familyTree_p_last_na_7358dc_idx',
        ),
        migrations.RenameIndex(
            model_name='person',
            new_name='familyTree__birth_d_7829ed_idx',
            old_name='familyTree_p_birth_d_8f4ccf_idx',
        ),
        migrations.RenameIndex(
            model_name='person',
            new_name='familyTree__death_d_681fb6_idx',
            old_name='familyTree_p_death_d_6d596f_idx',
        ),
        migrations.RenameIndex(
            model_name='person',
            new_name='familyTree__birth_p_3d2cd7_idx',
            old_name='familyTree_p_birth_p_49464e_idx',
        ),
        migrations.RenameIndex(
            model_name='person',
            new_name='familyTree__death_p_b2d2f1_idx',
            old_name='familyTree_p_death_p_19f7a6_idx',
        ),
        migrations.RenameIndex(
            model_name='relationship',
            new_name='familyTree__person1_609955_idx',
            old_name='familyTree_r_person1_19a7b2_idx',
        ),
        migrations.RenameIndex(
            model_name='relationship',
            new_name='familyTree__relatio_98e9d7_idx',
            old_name='familyTree_r_relatio_5531ca_idx',
        ),
        migrations.RenameIndex(
            model_name='relationship',
            new_name='familyTree__start_d_164464_idx',
            old_name='familyTree_r_start_d_9159bc_idx',
        ),
        migrations.RenameIndex(
            model_name='relationship',
            new_name='familyTree__end_dat_266112_idx',
            old_name='familyTree_r_end_dat_98f89b_idx',
        ),
    ]
